max_frames: 500
max_epoch: 20
eval_frames: 0
augment: False

## Training details
trainfunc: aamsoftmax
#seed: 100
lr_decay: 0.95

pretrained_model_path: /app/data/wav-lm/WavLM-Large.pt
train_list: /app/data/csv/train_manifest.csv
val_list: /app/data/csv/val_manifest.csv
test_list: /app/data/csv/test_manifest.csv
#save_ckpts: False

## Loss functions
nClasses: 1240

## Load and save
save_path: /app/data2/evaluate/

## Model definition
model: Baseline.Spk_Encoder

nOut: 256
port: 6754

# Greed Search
head_nb: 64
scale: 30
margin: 0.2
weight_finetuning_reg: 0.0008
LLRD_factor: 1.0
LR_Transformer: 2e-5
LR_MHFA: 0.0005
batch_size: 32
